// Code generated by github.com/phildrip/toe. DO NOT EDIT.

package stubs

import (
	"sync"
	"github.com/phildrip/toe/testdata/input/alias"
)

type StubAliasInterfaceOptions struct {
	WithLocking bool
}
type StubAliasInterfaceGetJobCall struct {
	Jobid alias.JobId
}
type StubAliasInterfaceGetJobReturns struct {
	String0 string
	Error1  error
}
type StubAliasInterfaceGetTaskCall struct {
	Taskid alias.TaskId
}
type StubAliasInterfaceGetTaskReturns struct {
	Error0 error
}
type StubAliasInterfaceProcessCall struct {
	Jobid  alias.JobId
	Taskid alias.TaskId
}
type StubAliasInterfaceProcessReturns struct {
	Entityid0 alias.EntityId
	Error1    error
}
type StubAliasInterface struct {
	mu             sync.Mutex
	isLocked       bool
	GetJobFunc     func(jobId alias.JobId) (string, error)
	GetJobCalls    []StubAliasInterfaceGetJobCall
	GetJobReturns  StubAliasInterfaceGetJobReturns
	GetTaskFunc    func(taskId alias.TaskId) error
	GetTaskCalls   []StubAliasInterfaceGetTaskCall
	GetTaskReturns StubAliasInterfaceGetTaskReturns
	ProcessFunc    func(jobId alias.JobId, taskId alias.TaskId) (alias.EntityId, error)
	ProcessCalls   []StubAliasInterfaceProcessCall
	ProcessReturns StubAliasInterfaceProcessReturns
}

func NewStubAliasInterface(opts StubAliasInterfaceOptions) *StubAliasInterface {
	return &StubAliasInterface{isLocked: opts.WithLocking}
}
func (s *StubAliasInterface) GetJob(jobId alias.JobId) (string, error) {
	if s.isLocked {
		s.mu.Lock()
		defer s.mu.Unlock()
	}
	s.GetJobCalls = append(s.GetJobCalls, StubAliasInterfaceGetJobCall{Jobid: jobId})
	if s.GetJobFunc != nil {
		return s.GetJobFunc(jobId)
	} else {
		return s.GetJobReturns.String0, s.GetJobReturns.Error1
	}
}
func (s *StubAliasInterface) GetTask(taskId alias.TaskId) error {
	if s.isLocked {
		s.mu.Lock()
		defer s.mu.Unlock()
	}
	s.GetTaskCalls = append(s.GetTaskCalls, StubAliasInterfaceGetTaskCall{Taskid: taskId})
	if s.GetTaskFunc != nil {
		return s.GetTaskFunc(taskId)
	} else {
		return s.GetTaskReturns.Error0
	}
}
func (s *StubAliasInterface) Process(jobId alias.JobId, taskId alias.TaskId) (alias.EntityId, error) {
	if s.isLocked {
		s.mu.Lock()
		defer s.mu.Unlock()
	}
	s.ProcessCalls = append(s.ProcessCalls, StubAliasInterfaceProcessCall{Jobid: jobId, Taskid: taskId})
	if s.ProcessFunc != nil {
		return s.ProcessFunc(jobId, taskId)
	} else {
		return s.ProcessReturns.Entityid0, s.ProcessReturns.Error1
	}
}
