// Code generated by github.com/phildrip/toe. DO NOT EDIT.

package stubs

import (
	"sync"
	"context"
)

type StubVariadicInterfaceOptions struct {
	WithLocking bool
}
type StubVariadicInterfaceExecuteCall struct {
	Ctx     context.Context
	Command string
	Args    []string
}
type StubVariadicInterfaceExecuteReturns struct {
	Int0   int
	Error1 error
}
type StubVariadicInterfaceLogCall struct {
	Level string
	Args  []interface {
	}
}
type StubVariadicInterfaceLogReturns struct {
	Error0 error
}
type StubVariadicInterfaceSimpleCall struct {
	A int
	B int
}
type StubVariadicInterfaceSimpleReturns struct {
	Int0 int
}
type StubVariadicInterface struct {
	mu             sync.Mutex
	isLocked       bool
	ExecuteFunc    func(ctx context.Context, command string, args ...string) (int, error)
	ExecuteCalls   []StubVariadicInterfaceExecuteCall
	ExecuteReturns StubVariadicInterfaceExecuteReturns
	LogFunc        func(level string, args ...interface {
	}) error
	LogCalls      []StubVariadicInterfaceLogCall
	LogReturns    StubVariadicInterfaceLogReturns
	SimpleFunc    func(a int, b int) int
	SimpleCalls   []StubVariadicInterfaceSimpleCall
	SimpleReturns StubVariadicInterfaceSimpleReturns
}

func NewStubVariadicInterface(opts StubVariadicInterfaceOptions) *StubVariadicInterface {
	return &StubVariadicInterface{isLocked: opts.WithLocking}
}
func (s *StubVariadicInterface) Execute(ctx context.Context, command string, args ...string) (int, error) {
	if s.isLocked {
		s.mu.Lock()
		defer s.mu.Unlock()
	}
	s.ExecuteCalls = append(s.ExecuteCalls, StubVariadicInterfaceExecuteCall{Ctx: ctx, Command: command, Args: args})
	if s.ExecuteFunc != nil {
		return s.ExecuteFunc(ctx, command, args...)
	} else {
		return s.ExecuteReturns.Int0, s.ExecuteReturns.Error1
	}
}
func (s *StubVariadicInterface) Log(level string, args ...interface {
}) error {
	if s.isLocked {
		s.mu.Lock()
		defer s.mu.Unlock()
	}
	s.LogCalls = append(s.LogCalls, StubVariadicInterfaceLogCall{Level: level, Args: args})
	if s.LogFunc != nil {
		return s.LogFunc(level, args...)
	} else {
		return s.LogReturns.Error0
	}
}
func (s *StubVariadicInterface) Simple(a int, b int) int {
	if s.isLocked {
		s.mu.Lock()
		defer s.mu.Unlock()
	}
	s.SimpleCalls = append(s.SimpleCalls, StubVariadicInterfaceSimpleCall{A: a, B: b})
	if s.SimpleFunc != nil {
		return s.SimpleFunc(a, b)
	} else {
		return s.SimpleReturns.Int0
	}
}
