// Code generated by github.com/phildrip/toe. DO NOT EDIT.

package stubs

import (
	"sync"
	"context"
	"github.com/phildrip/toe/testdata/input/external/types"
	"io"
)

type StubExternalInterfaceOptions struct {
	WithLocking bool
}
type StubExternalInterfaceDeleteCall struct {
	Ctx          context.Context
	Id           types.BlobId
	Collectionid types.CollectionId
}
type StubExternalInterfaceDeleteReturns struct {
	Error0 error
}
type StubExternalInterfaceGetCall struct {
	Ctx context.Context
	Id  types.BlobId
}
type StubExternalInterfaceGetReturns struct {
	String0 string
	Error1  error
}
type StubExternalInterfaceSetCall struct {
	Ctx     context.Context
	Id      types.BlobId
	Content io.Reader
}
type StubExternalInterfaceSetReturns struct {
	Error0 error
}
type StubExternalInterface struct {
	mu            sync.Mutex
	isLocked      bool
	DeleteFunc    func(ctx context.Context, id types.BlobId, collectionId types.CollectionId) error
	DeleteCalls   []StubExternalInterfaceDeleteCall
	DeleteReturns StubExternalInterfaceDeleteReturns
	GetFunc       func(ctx context.Context, id types.BlobId) (string, error)
	GetCalls      []StubExternalInterfaceGetCall
	GetReturns    StubExternalInterfaceGetReturns
	SetFunc       func(ctx context.Context, id types.BlobId, content io.Reader) error
	SetCalls      []StubExternalInterfaceSetCall
	SetReturns    StubExternalInterfaceSetReturns
}

func NewStubExternalInterface(opts StubExternalInterfaceOptions) *StubExternalInterface {
	return &StubExternalInterface{isLocked: opts.WithLocking}
}
func (s *StubExternalInterface) Delete(ctx context.Context, id types.BlobId, collectionId types.CollectionId) error {
	if s.isLocked {
		s.mu.Lock()
		defer s.mu.Unlock()
	}
	s.DeleteCalls = append(s.DeleteCalls, StubExternalInterfaceDeleteCall{Ctx: ctx, Id: id, Collectionid: collectionId})
	if s.DeleteFunc != nil {
		return s.DeleteFunc(ctx, id, collectionId)
	} else {
		return s.DeleteReturns.Error0
	}
}
func (s *StubExternalInterface) Get(ctx context.Context, id types.BlobId) (string, error) {
	if s.isLocked {
		s.mu.Lock()
		defer s.mu.Unlock()
	}
	s.GetCalls = append(s.GetCalls, StubExternalInterfaceGetCall{Ctx: ctx, Id: id})
	if s.GetFunc != nil {
		return s.GetFunc(ctx, id)
	} else {
		return s.GetReturns.String0, s.GetReturns.Error1
	}
}
func (s *StubExternalInterface) Set(ctx context.Context, id types.BlobId, content io.Reader) error {
	if s.isLocked {
		s.mu.Lock()
		defer s.mu.Unlock()
	}
	s.SetCalls = append(s.SetCalls, StubExternalInterfaceSetCall{Ctx: ctx, Id: id, Content: content})
	if s.SetFunc != nil {
		return s.SetFunc(ctx, id, content)
	} else {
		return s.SetReturns.Error0
	}
}
