// Code generated by github.com/phildrip/toe. DO NOT EDIT.

package stubs

import "sync"

type StubCalculatorOptions struct {
	WithLocking bool
}
type StubCalculatorAddCall struct {
	A int
	B int
}
type StubCalculatorAddReturns struct {
	Int0 int
}
type StubCalculatorSubtractCall struct {
	A int
	B int
}
type StubCalculatorSubtractReturns struct {
	Int0   int
	Error1 error
}
type StubCalculator struct {
	mu              sync.Mutex
	isLocked        bool
	AddFunc         func(a int, b int) int
	AddCalls        []StubCalculatorAddCall
	AddReturns      StubCalculatorAddReturns
	SubtractFunc    func(a int, b int) (int, error)
	SubtractCalls   []StubCalculatorSubtractCall
	SubtractReturns StubCalculatorSubtractReturns
}

func NewStubCalculator(opts StubCalculatorOptions) *StubCalculator {
	return &StubCalculator{isLocked: opts.WithLocking}
}
func (s *StubCalculator) Add(a int, b int) int {
	if s.isLocked {
		s.mu.Lock()
		defer s.mu.Unlock()
	}
	s.AddCalls = append(s.AddCalls, StubCalculatorAddCall{A: a, B: b})
	if s.AddFunc != nil {
		return s.AddFunc(a, b)
	} else {
		return s.AddReturns.Int0
	}
}
func (s *StubCalculator) Subtract(a int, b int) (int, error) {
	if s.isLocked {
		s.mu.Lock()
		defer s.mu.Unlock()
	}
	s.SubtractCalls = append(s.SubtractCalls, StubCalculatorSubtractCall{A: a, B: b})
	if s.SubtractFunc != nil {
		return s.SubtractFunc(a, b)
	} else {
		return s.SubtractReturns.Int0, s.SubtractReturns.Error1
	}
}
